name: Update README

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Makefile on README
        run: |
          echo '```bash' > docs/README.md
          cat Makefile >> docs/README.md
          echo '```' >> docs/README.md
          cat docs/README.md
